$(document).ready(function(){
	$('#p_state').change(function(){
		//var p_state = $('#p_state').val();
		
		var p_state=$(this).val();
		//alert(p_state);
		
		if(p_state=="ABIA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Aba North">Aba North</option>');
			$('#p_lga').append('<option value="Aba South">Aba South</option>');
			$('#p_lga').append('<option value="Arochukwu">Arochukwu</option>');
			$('#p_lga').append('<option value="Bende">Bende</option>');
			$('#p_lga').append('<option value="Ikwuano">Ikwuano</option>');
			$('#p_lga').append('<option value="Isiala-Ngwa North">Isiala-Ngwa North</option>');
			$('#p_lga').append('<option value="Isiala-Ngwa South">Isiala-Ngwa South</option>');
			$('#p_lga').append('<option value="Isuikwato">Isuikwato</option>');
			$('#p_lga').append('<option value="Obi Nwa">Obi Nwa</option>');
			$('#p_lga').append('<option value="Ohafia">Ohafia</option>');
			$('#p_lga').append('<option value="Osisioma">Osisioma</option>');
			$('#p_lga').append('<option value="Ngwa">Ngwa</option>');
			$('#p_lga').append('<option value="Ugwunagbo">Ugwunagbo</option>');
			$('#p_lga').append('<option value="Ukwa East">Ukwa East</option>');
			$('#p_lga').append('<option value="Ukwa West">Ukwa West</option>');
			$('#p_lga').append('<option value="Umuahia North">Umuahia North</option>');
			$('#p_lga').append('<option value="Umuahia South">Umuahia South</option>');
			$('#p_lga').append('<option value="Umu-Neochi">Umu-Neochi</option>');
		}
		else if(p_state=="ADAMAWA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Demsa">Demsa</option>');
			$('#p_lga').append('<option value="Fufore">Fufore</option>');
			$('#p_lga').append('<option value="Ganye">Ganye</option>');
			$('#p_lga').append('<option value="Girei">Girei</option>');
			$('#p_lga').append('<option value="Gombi">Gombi</option>');
			$('#p_lga').append('<option value="Guyuk">Guyuk</option>');
			$('#p_lga').append('<option value="Hong">Hong</option>');
			$('#p_lga').append('<option value="Jada">Jada</option>');
			$('#p_lga').append('<option value="Lamurde">Lamurde</option>');
			$('#p_lga').append('<option value="Madagali">Madagali</option>');
			$('#p_lga').append('<option value="Maiha">Maiha</option>');
			$('#p_lga').append('<option value="Mayo Belwa">Mayo Belwa</option>');
			$('#p_lga').append('<option value="Michika">Michika</option>');
			$('#p_lga').append('<option value="Mubi North">Mubi North</option>');
			$('#p_lga').append('<option value="Mubi South">Mubi South</option>');
			$('#p_lga').append('<option value="Numan">Numan</option>');
			$('#p_lga').append('<option value="Shelleng">Shelleng</option>');
			$('#p_lga').append('<option value="Song">Song</option>');
			$('#p_lga').append('<option value="Toungo">Toungo</option>');
			$('#p_lga').append('<option value="Yola North">Yola North</option>');
			$('#p_lga').append('<option value="Yola South">Yola South</option>');
		}
		else if(p_state=="AKWA-IBOM"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Abak">Abak</option>');
			$('#p_lga').append('<option value="Eastern Obolo">Eastern Obolo</option>');
			$('#p_lga').append('<option value="Eket">Eket</option>');
			$('#p_lga').append('<option value="Esit Eket">Esit Eket</option>');
			$('#p_lga').append('<option value="Essien Udim">Essien Udim</option>');
			$('#p_lga').append('<option value="Etim Ekpo">Etim Ekpo</option>');
			$('#p_lga').append('<option value="Etinan">Etinan</option>');
			$('#p_lga').append('<option value="Ibeno">Ibeno</option>');
			$('#p_lga').append('<option value="Ibesikpo Asutan">Ibesikpo Asutan</option>');
			$('#p_lga').append('<option value="Ibiono Ibom">Ibiono Ibom</option>');
			$('#p_lga').append('<option value="Ika">Ika</option>');
			$('#p_lga').append('<option value="Ikono">Ikono</option>');
			$('#p_lga').append('<option value="Ikot Abasi">Ikot Abasi</option>');
			$('#p_lga').append('<option value="Ikot Ekpene">Ikot Ekpene</option>');
			$('#p_lga').append('<option value="Ini">Ini</option>');
			$('#p_lga').append('<option value="Itu">Itu</option>');
			$('#p_lga').append('<option value="Mbo">Mbo</option>');
			$('#p_lga').append('<option value="Mkpat Enin">Mkpat Enin</option>');
			$('#p_lga').append('<option value="Nsit Atai">Nsit Atai</option>');
			$('#p_lga').append('<option value="Nsit Ibom">Nsit Ibom</option>');
			$('#p_lga').append('<option value="Nsit Ubium">Nsit Ubium</option>');
			$('#p_lga').append('<option value="Obot Akara">Obot Akara</option>');
			$('#p_lga').append('<option value="Okobo">Okobo</option>');
			$('#p_lga').append('<option value="Onna">Onna</option>');
			$('#p_lga').append('<option value="Oron">Oron</option>');
			$('#p_lga').append('<option value="Oruk Anam">Oruk Anam</option>');
			$('#p_lga').append('<option value="Udung Uko">Udung Uko</option>');
			$('#p_lga').append('<option value="Ukanafun">Ukanafun</option>');
			$('#p_lga').append('<option value="Uruan">Uruan</option>');
			$('#p_lga').append('<option value="Urue-Offong/Oruko">Urue-Offong/Oruko</option>');
			$('#p_lga').append('<option value="Uyo">Uyo</option>');
		}
		else if(p_state=="ANAMBRA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Aguata">Aguata</option>');
			$('#p_lga').append('<option value="Anambra East">Anambra East</option>');
			$('#p_lga').append('<option value="Anambra West">Anambra West</option>');
			$('#p_lga').append('<option value="Anaocha">Anaocha</option>');
			$('#p_lga').append('<option value="Awka North">Awka North</option>');
			$('#p_lga').append('<option value="Awka South">Awka South</option>');
			$('#p_lga').append('<option value="Ayamelum">Ayamelum</option>');
			$('#p_lga').append('<option value="Dunukofia">Dunukofia</option>');
			$('#p_lga').append('<option value="Ekwusigo">Ekwusigo</option>');
			$('#p_lga').append('<option value="Idemili North">Idemili North</option>');
			$('#p_lga').append('<option value="Idemili south">Idemili south</option>');
			$('#p_lga').append('<option value="Ihiala">Ihiala</option>');
			$('#p_lga').append('<option value="Njikoka">Njikoka</option>');
			$('#p_lga').append('<option value="Nnewi North">Nnewi North</option>');
			$('#p_lga').append('<option value="Nnewi South">Nnewi South</option>');
			$('#p_lga').append('<option value="Ogbaru">Ogbaru</option>');
			$('#p_lga').append('<option value="Onitsha North">Onitsha North</option>');
			$('#p_lga').append('<option value="Onitsha South">Onitsha South</option>');
			$('#p_lga').append('<option value="Orumba North">Orumba North</option>');
			$('#p_lga').append('<option value="Orumba South">Orumba South</option>');
			$('#p_lga').append('<option value="Oyi">Oyi</option>');
		}
		else if(p_state=="BAUCHI"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Alkaleri">Alkaleri</option>');
			$('#p_lga').append('<option value="Bauchi">Bauchi</option>');
			$('#p_lga').append('<option value="Bogoro">Bogoro</option>');
			$('#p_lga').append('<option value="Damban">Damban</option>');
			$('#p_lga').append('<option value="Darazo">Darazo</option>');
			$('#p_lga').append('<option value="Dass">Dass</option>');
			$('#p_lga').append('<option value="Gamawa">Gamawa</option>');
			$('#p_lga').append('<option value="Ganjuwa">Ganjuwa</option>');
			$('#p_lga').append('<option value="Giade">Giade</option>');
			$('#p_lga').append('<option value="Itas/Gadau">Itas/Gadau</option>');
			$('#p_lga').append('<option value="Jamaare">Jamaare</option>');
			$('#p_lga').append('<option value="Katagum">Katagum</option>');
			$('#p_lga').append('<option value="Kirfi">Kirfi</option>');
			$('#p_lga').append('<option value="Misau">Misau</option>');
			$('#p_lga').append('<option value="Ningi">Ningi</option>');
			$('#p_lga').append('<option value="Shira">Shira</option>');
			$('#p_lga').append('<option value="Tafawa-Balewa">Tafawa-Balewa</option>');
			$('#p_lga').append('<option value="Toro">Toro</option>');
			$('#p_lga').append('<option value="Warji">Warji</option>');
			$('#p_lga').append('<option value="Zaki">Zaki</option>');
		}
		else if(p_state=="BAYELSA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Brass">Brass</option>');
			$('#p_lga').append('<option value="Ekeremor">Ekeremor</option>');
			$('#p_lga').append('<option value="Kolokuma/Opokuma">Kolokuma/Opokuma</option>');
			$('#p_lga').append('<option value="Nembe">Nembe</option>');
			$('#p_lga').append('<option value="Ogbia">Ogbia</option>');
			$('#p_lga').append('<option value="Sagbama">Sagbama</option>');
			$('#p_lga').append('<option value="Southern Jaw">Southern Jaw</option>');
			$('#p_lga').append('<option value="Yenegoa">Yenegoa</option>');
		}
		else if(p_state=="BENUE"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Ado">Ado</option>');
			$('#p_lga').append('<option value="Agatu">Agatu</option>');
			$('#p_lga').append('<option value="Apa">Apa</option>');
			$('#p_lga').append('<option value="Buruku">Buruku</option>');
			$('#p_lga').append('<option value="Gboko">Gboko</option>');
			$('#p_lga').append('<option value="Guma">Guma</option>');
			$('#p_lga').append('<option value="Gwer East">Gwer East</option>');
			$('#p_lga').append('<option value="Gwer West">Gwer West</option>');
			$('#p_lga').append('<option value="Katsina-Ala">Katsina-Ala</option>');
			$('#p_lga').append('<option value="Konshisha">Konshisha</option>');
			$('#p_lga').append('<option value="Kwande">Kwande</option>');
			$('#p_lga').append('<option value="Logo">Logo</option>');
			$('#p_lga').append('<option value="Makurdi">Makurdi</option>');
			$('#p_lga').append('<option value="Obi">Obi</option>');
			$('#p_lga').append('<option value="Ogbadibo">Ogbadibo</option>');
			$('#p_lga').append('<option value="Oju">Oju</option>');
			$('#p_lga').append('<option value="Okpokwu">Okpokwu</option>');
			$('#p_lga').append('<option value="Ohimini">Ohimini</option>');
			$('#p_lga').append('<option value="Oturkpo">Oturkpo</option>');
			$('#p_lga').append('<option value="Tarka">Tarka</option>');
			$('#p_lga').append('<option value="Ukum">Ukum</option>');
			$('#p_lga').append('<option value="Ushongo">Ushongo</option>');
			$('#p_lga').append('<option value="Vandeikya">Vandeikya</option>');
		}
		else if(p_state=="BORNO"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Abadam">Abadam</option>');
			$('#p_lga').append('<option value="Askira/Uba">Askira/Uba</option>');
			$('#p_lga').append('<option value="Bama">Bama</option>');
			$('#p_lga').append('<option value="Bayo">Bayo</option>');
			$('#p_lga').append('<option value="Biu">Biu</option>');
			$('#p_lga').append('<option value="Chibok">Chibok</option>');
			$('#p_lga').append('<option value="Damboa">Damboa</option>');
			$('#p_lga').append('<option value="Dikwa">Dikwa</option>');
			$('#p_lga').append('<option value="Gubio">Gubio</option>');
			$('#p_lga').append('<option value="Guzamala">Guzamala</option>');
			$('#p_lga').append('<option value="Gwoza">Gwoza</option>');
			$('#p_lga').append('<option value="Hawul">Hawul</option>');
			$('#p_lga').append('<option value="Jere">Jere</option>');
			$('#p_lga').append('<option value="Kaga">Kaga</option>');
			$('#p_lga').append('<option value="Kala/Balge">Kala/Balge</option>');
			$('#p_lga').append('<option value="Konduga">Konduga</option>');
			$('#p_lga').append('<option value="Kukawa">Kukawa</option>');
			$('#p_lga').append('<option value="Kwaya Kusar">Kwaya Kusar</option>');
			$('#p_lga').append('<option value="Mafa">Mafa</option>');
			$('#p_lga').append('<option value="Magumeri">Magumeri</option>');
			$('#p_lga').append('<option value="Maiduguri">Maiduguri</option>');
			$('#p_lga').append('<option value="Marte">Marte</option>');
			$('#p_lga').append('<option value="Mobbar">Mobbar</option>');
			$('#p_lga').append('<option value="Monguno">Monguno</option>');
			$('#p_lga').append('<option value="Ngala">Ngala</option>');
			$('#p_lga').append('<option value="Nganzai">Nganzai</option>');
			$('#p_lga').append('<option value="Shani">Shani</option>');
		}
		else if(p_state=="CROSS RIVER"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Abi">Abi</option>');
			$('#p_lga').append('<option value="Akamkpa">Akamkpa</option>');
			$('#p_lga').append('<option value="Akpabuyo">Akpabuyo</option>');
			$('#p_lga').append('<option value="Bakassi">Bakassi</option>');
			$('#p_lga').append('<option value="Bekwara">Bekwara</option>');
			$('#p_lga').append('<option value="Biase">Biase</option>');
			$('#p_lga').append('<option value="Boki">Boki</option>');
			$('#p_lga').append('<option value="Calabar Municipality">Calabar Municipality</option>');
			$('#p_lga').append('<option value="Calabar South">Calabar South</option>');
			$('#p_lga').append('<option value="Etung">Etung</option>');
			$('#p_lga').append('<option value="Ikom">Ikom</option>');
			$('#p_lga').append('<option value="Obanliku">Obanliku</option>');
			$('#p_lga').append('<option value="Obubra">Obubra</option>');
			$('#p_lga').append('<option value="Obudu">Obudu</option>');
			$('#p_lga').append('<option value="Odukpani">Odukpani</option>');
			$('#p_lga').append('<option value="Ogoja">Ogoja</option>');
			$('#p_lga').append('<option value="Yala">Yala</option>');
			$('#p_lga').append('<option value="Yarkur">Yarkur</option>');
		}
		else if(p_state=="DELTA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Aniocha">Aniocha</option>');
			$('#p_lga').append('<option value="Aniocha South">Aniocha South</option>');
			$('#p_lga').append('<option value="Bomadi">Bomadi</option>');
			$('#p_lga').append('<option value="Burutu">Burutu</option>');
			$('#p_lga').append('<option value="Ethiope East">Ethiope East</option>');
			$('#p_lga').append('<option value="Ethiope West">Ethiope West</option>');
			$('#p_lga').append('<option value="Ika North-East">Ika North-East</option>');
			$('#p_lga').append('<option value="Ika South">Ika South</option>');
			$('#p_lga').append('<option value="Isoko North">Isoko North</option>');
			$('#p_lga').append('<option value="Isoko south">Isoko south</option>');
			$('#p_lga').append('<option value="Ndokwa East">Ndokwa East</option>');
			$('#p_lga').append('<option value="Ndokwa West">Ndokwa West</option>');
			$('#p_lga').append('<option value="Okpe">Okpe</option>');
			$('#p_lga').append('<option value="Oshimili">Oshimili</option>');
			$('#p_lga').append('<option value="Oshimili North">Oshimili North</option>');
			$('#p_lga').append('<option value="Oshimili South">Oshimili South</option>');
			$('#p_lga').append('<option value="Patani">Patani</option>');
			$('#p_lga').append('<option value="Sapele">Sapele</option>');
			$('#p_lga').append('<option value="Udu">Udu</option>');
			$('#p_lga').append('<option value="Ughelli North">Ughelli North</option>');
			$('#p_lga').append('<option value="Ughelli South">Ughelli South</option>');
			$('#p_lga').append('<option value="Ukwani">Ukwani</option>');
			$('#p_lga').append('<option value="Uvwie">Uvwie</option>');
			$('#p_lga').append('<option value="Warri Central">Warri Central</option>');
			$('#p_lga').append('<option value="Warri North">Warri North</option>');
			$('#p_lga').append('<option value="Warri South">Warri South</option>');
		}
		else if(p_state=="EBONYI"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Abakaliki">Abakaliki</option>');
			$('#p_lga').append('<option value="Afikpo North">Afikpo North</option>');
			$('#p_lga').append('<option value="Afikpo South">Afikpo South</option>');
			$('#p_lga').append('<option value="Ebonyi">Ebonyi</option>');
			$('#p_lga').append('<option value="Ezza">Ezza</option>');
			$('#p_lga').append('<option value="Ezza South">Ezza South</option>');
			$('#p_lga').append('<option value="Ikwo">Ikwo</option>');
			$('#p_lga').append('<option value="Ishielu">Ishielu</option>');
			$('#p_lga').append('<option value="Izzi">Izzi</option>');
			$('#p_lga').append('<option value="Ivo">Ivo</option>');
			$('#p_lga').append('<option value="Ohaozara">Ohaozara</option>');
			$('#p_lga').append('<option value="Ohaukwu">Ohaukwu</option>');
			$('#p_lga').append('<option value="Onicha">Onicha</option>');
		}
		else if(p_state=="EDO"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Akoko-Edo">Akoko-Edo</option>');
			$('#p_lga').append('<option value="Central">Central</option>');
			$('#p_lga').append('<option value="Egor">Egor</option>');
			$('#p_lga').append('<option value="Esan Central">Esan Central</option>');
			$('#p_lga').append('<option value="Esan North-East">Esan North-East</option>');
			$('#p_lga').append('<option value="Esan South-East">Esan South-East</option>');
			$('#p_lga').append('<option value="Esan West">Esan West</option>');
			$('#p_lga').append('<option value="Etsako Central">Etsako Central</option>');
			$('#p_lga').append('<option value="Etsako East">Etsako East</option>');
			$('#p_lga').append('<option value="Etsako West">Etsako West</option>');
			$('#p_lga').append('<option value="Igueben">Igueben</option>');
			$('#p_lga').append('<option value="Oredo">Oredo</option>');
			$('#p_lga').append('<option value="Orhionwon">Orhionwon</option>');
			$('#p_lga').append('<option value="Owan East">Owan East</option>');
			$('#p_lga').append('<option value="Owan West">Owan West</option>');
			$('#p_lga').append('<option value="Ovia South-East">Ovia South-East</option>');
			$('#p_lga').append('<option value="Ovia SouthWest">Ovia SouthWest</option>');
			$('#p_lga').append('<option value="Uhunmwonde">Uhunmwonde</option>');
			$('#p_lga').append('<option value="Ukpoba">Ukpoba</option>');
		}
		else if(p_state=="EKITI"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Ado">Ado</option>');
			$('#p_lga').append('<option value="Efon">Efon</option>');
			$('#p_lga').append('<option value="Ekiti South-West">Ekiti South-West</option>');
			$('#p_lga').append('<option value="Ekiti-East">Ekiti-East</option>');
			$('#p_lga').append('<option value="Ekiti-West">Ekiti-West</option>');
			$('#p_lga').append('<option value="Emure/Ise/Orun">Emure/Ise/Orun</option>');
			$('#p_lga').append('<option value="Gbonyin">Gbonyin</option>');
			$('#p_lga').append('<option value="Ido/Osi">Ido/Osi</option>');
			$('#p_lga').append('<option value="Ijero">Ijero</option>');
			$('#p_lga').append('<option value="Ikere">Ikere</option>');
			$('#p_lga').append('<option value="Ikole">Ikole</option>');
			$('#p_lga').append('<option value="Ilejemeje">Ilejemeje</option>');
			$('#p_lga').append('<option value="Irepodun">Irepodun</option>');
			$('#p_lga').append('<option value="Ise/Orun">Ise/Orun</option>');
			$('#p_lga').append('<option value="Moba">Moba</option>');
			$('#p_lga').append('<option value="Oye">Oye</option>');
			$('#p_lga').append('<option value=""></option>');
		}
		else if(p_state=="ENUGU"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Aninri">Aninri</option>');
			$('#p_lga').append('<option value="Awgu">Awgu</option>');
			$('#p_lga').append('<option value="Enugu Eas">Enugu Eas</option>');
			$('#p_lga').append('<option value="Enugu North">Enugu North</option>');
			$('#p_lga').append('<option value="Enugu South">Enugu South</option>');
			$('#p_lga').append('<option value="Enugu">Enugu</option>');
			$('#p_lga').append('<option value="Ezeagu">Ezeagu</option>');
			$('#p_lga').append('<option value="Igbo-Ekiti">Igbo-Ekiti</option>');
			$('#p_lga').append('<option value="IgboEze North">IgboEze North</option>');
			$('#p_lga').append('<option value="Igbo-Eze South">Igbo-Eze South</option>');
			$('#p_lga').append('<option value="Isi-Uzo">Isi-Uzo</option>');
			$('#p_lga').append('<option value="Nkanu">Nkanu</option>');
			$('#p_lga').append('<option value="Nkanu East">Nkanu East</option>');
			$('#p_lga').append('<option value="Nsukka">Nsukka</option>');
			$('#p_lga').append('<option value="Oji-River">Oji-River</option>');
			$('#p_lga').append('<option value="Udenu">Udenu</option>');
			$('#p_lga').append('<option value="Udi">Udi</option>');
			$('#p_lga').append('<option value="Uzo-Uwani">Uzo-Uwani</option>');
		}
		else if(p_state=="FCT-ABUJA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Gwagwalada">Gwagwalada</option>');
			$('#p_lga').append('<option value="Kuje">Kuje</option>');
			$('#p_lga').append('<option value="Abaji">Abaji</option>');
			$('#p_lga').append('<option value="Abuja Municipal">Abuja Municipal</option>');
			$('#p_lga').append('<option value="Bwari">Bwari</option>');
			$('#p_lga').append('<option value="Kwali">Kwali</option>');
		}
		else if(p_state=="GOMBE"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Akko">Akko</option>');
			$('#p_lga').append('<option value="Balanga">Balanga</option>');
			$('#p_lga').append('<option value="Billiri">Billiri</option>');
			$('#p_lga').append('<option value="Dukku">Dukku</option>');
			$('#p_lga').append('<option value="Funakaye">Funakaye</option>');
			$('#p_lga').append('<option value="Gombe">Gombe</option>');
			$('#p_lga').append('<option value="Kaltungo">Kaltungo</option>');
			$('#p_lga').append('<option value="Kwami">Kwami</option>');
			$('#p_lga').append('<option value="Nafada/Bajoga">Nafada/Bajoga</option>');
			$('#p_lga').append('<option value="Shomgom">Shomgom</option>');
			$('#p_lga').append('<option value="Yamaltu/Deba">Yamaltu/Deba</option>');
		}
		else if(p_state=="IMO"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Aboh-Mbaise">Aboh-Mbaise</option>');
			$('#p_lga').append('<option value="Ahiazu-Mbaise">Ahiazu-Mbaise</option>');
			$('#p_lga').append('<option value="Ehime-Mbano">Ehime-Mbano</option>');
			$('#p_lga').append('<option value="Ezinihitte">Ezinihitte</option>');
			$('#p_lga').append('<option value="Ideato North">Ideato North</option>');
			$('#p_lga').append('<option value="Ideato South">Ideato South</option>');
			$('#p_lga').append('<option value="Ihitte/Uboma">Ihitte/Uboma</option>');
			$('#p_lga').append('<option value="Ikeduru">Ikeduru</option>');
			$('#p_lga').append('<option value="Isiala Mbano">Isiala Mbano</option>');
			$('#p_lga').append('<option value="Isu">Isu</option>');
			$('#p_lga').append('<option value="Mbaitoli">Mbaitoli</option>');
			$('#p_lga').append('<option value="Ngor-Okpala">Ngor-Okpala</option>');
			$('#p_lga').append('<option value="Njaba">Njaba</option>');
			$('#p_lga').append('<option value="Nkwerre">Nkwerre</option>');
			$('#p_lga').append('<option value="Nwangele">Nwangele</option>');
			$('#p_lga').append('<option value="Obowo">Obowo</option>');
			$('#p_lga').append('<option value="Oguta">Oguta</option>');
			$('#p_lga').append('<option value="Ohaji/Egbema">Ohaji/Egbema</option>');
			$('#p_lga').append('<option value="Okigwe">Okigwe</option>');
			$('#p_lga').append('<option value="Orlu">Orlu</option>');
			$('#p_lga').append('<option value="Orsu">Orsu</option>');
			$('#p_lga').append('<option value="Oru East">Oru East</option>');
			$('#p_lga').append('<option value="Oru West">Oru West</option>');
			$('#p_lga').append('<option value="Owerri North">Owerri North</option>');
			$('#p_lga').append('<option value="Owerri West">Owerri West</option>');
			$('#p_lga').append('<option value="Owerri-Municipal">Owerri-Municipal</option>');
		}
		else if(p_state=="JIGAWA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Auyo">Auyo</option>');
			$('#p_lga').append('<option value="Babura">Babura</option>');
			$('#p_lga').append('<option value="Biriniwa">Biriniwa</option>');
			$('#p_lga').append('<option value="Birni Kudu">Birni Kudu</option>');
			$('#p_lga').append('<option value="Buji">Buji</option>');
			$('#p_lga').append('<option value="Dutse">Dutse</option>');
			$('#p_lga').append('<option value="Gagarawa">Gagarawa</option>');
			$('#p_lga').append('<option value="Garki">Garki</option>');
			$('#p_lga').append('<option value="Gumel">Gumel</option>');
			$('#p_lga').append('<option value="Guri">Guri</option>');
			$('#p_lga').append('<option value="Gwaram">Gwaram</option>');
			$('#p_lga').append('<option value="Gwiwa">Gwiwa</option>');
			$('#p_lga').append('<option value="Hadejia">Hadejia</option>');
			$('#p_lga').append('<option value="Jahun">Jahun</option>');
			$('#p_lga').append('<option value="Kafin Hausa">Kafin Hausa</option>');
			$('#p_lga').append('<option value="Kaugama Kazaure">Kaugama Kazaure</option>');
			$('#p_lga').append('<option value="Kiri Kasamma">Kiri Kasamma</option>');
			$('#p_lga').append('<option value="Kiyawa">Kiyawa</option>');
			$('#p_lga').append('<option value="Maigatari">Maigatari</option>');
			$('#p_lga').append('<option value="Malam Madori">Malam Madori</option>');
			$('#p_lga').append('<option value="Miga">Miga</option>');
			$('#p_lga').append('<option value="Ringim">Ringim</option>');
			$('#p_lga').append('<option value="Roni">Roni</option>');
			$('#p_lga').append('<option value="Sule-Tankarkar">Sule-Tankarkar</option>');
			$('#p_lga').append('<option value="Taura">Taura</option>');
			$('#p_lga').append('<option value="Yankwashi">Yankwashi</option>');
		}
		else if(p_state=="KADUNA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Birni-Gwari">Birni-Gwari</option>');
			$('#p_lga').append('<option value="Chikun">Chikun</option>');
			$('#p_lga').append('<option value="Giwa">Giwa</option>');
			$('#p_lga').append('<option value="Igabi">Igabi</option>');
			$('#p_lga').append('<option value="Ikara">Ikara</option>');
			$('#p_lga').append('<option value="Jaba">Jaba</option>');
			$('#p_lga').append('<option value="Jema-a">Jema-a</option>');
			$('#p_lga').append('<option value="Kachia">Kachia</option>');
			$('#p_lga').append('<option value="Kaduna North">Kaduna North</option>');
			$('#p_lga').append('<option value="Kaduna South">Kaduna South</option>');
			$('#p_lga').append('<option value="Kagarko">Kagarko</option>');
			$('#p_lga').append('<option value="Kajuru">Kajuru</option>');
			$('#p_lga').append('<option value="Kaura">Kaura</option>');
			$('#p_lga').append('<option value="Kauru">Kauru</option>');
			$('#p_lga').append('<option value="Kubau">Kubau</option>');
			$('#p_lga').append('<option value="Kudan">Kudan</option>');
			$('#p_lga').append('<option value="Lere">Lere</option>');
			$('#p_lga').append('<option value="Makarfi">Makarfi</option>');
			$('#p_lga').append('<option value="Sabon-Gari">Sabon-Gari</option>');
			$('#p_lga').append('<option value="Sanga">Sanga</option>');
			$('#p_lga').append('<option value="Soba">Soba</option>');
			$('#p_lga').append('<option value="Zango-Kataf">Zango-Kataf</option>');
			$('#p_lga').append('<option value="Zaria">Zaria</option>');
		}
		else if(p_state=="KANO"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Ajingi">Ajingi</option>');
			$('#p_lga').append('<option value="Albasu">Albasu</option>');
			$('#p_lga').append('<option value="Bagwai">Bagwai</option>');
			$('#p_lga').append('<option value="Bebeji">Bebeji</option>');
			$('#p_lga').append('<option value="Bichi">Bichi</option>');
			$('#p_lga').append('<option value="Bunkure">Bunkure</option>');
			$('#p_lga').append('<option value="Dala">Dala</option>');
			$('#p_lga').append('<option value="Dambatta">Dambatta</option>');
			$('#p_lga').append('<option value="Dawakin Kudu">Dawakin Kudu</option>');
			$('#p_lga').append('<option value="Dawakin Tofa">Dawakin Tofa</option>');
			$('#p_lga').append('<option value="Doguwa">Doguwa</option>');
			$('#p_lga').append('<option value="Fagge">Fagge</option>');
			$('#p_lga').append('<option value="Gabasawa">Gabasawa</option>');
			$('#p_lga').append('<option value="Garko">Garko</option>');
			$('#p_lga').append('<option value="Garum">Garum</option>');
			$('#p_lga').append('<option value="Gaya">Gaya</option>');
			$('#p_lga').append('<option value="Gezawa">Gezawa</option>');
			$('#p_lga').append('<option value="Gwale">Gwale</option>');
			$('#p_lga').append('<option value="Gwarzo">Gwarzo</option>');
			$('#p_lga').append('<option value="Kabo">Kabo</option>');
			$('#p_lga').append('<option value="Kano Municipal">Kano Municipal</option>');
			$('#p_lga').append('<option value="Karaye">Karaye</option>');
			$('#p_lga').append('<option value="Kibiya">Kibiya</option>');
			$('#p_lga').append('<option value="Kiru">Kiru</option>');
			$('#p_lga').append('<option value="Kumbotso">Kumbotso</option>');
			$('#p_lga').append('<option value="Kunchi">Kunchi</option>');
			$('#p_lga').append('<option value="Kura">Kura</option>');
			$('#p_lga').append('<option value="Madobi">Madobi</option>');
			$('#p_lga').append('<option value="Makoda">Makoda</option>');
			$('#p_lga').append('<option value="Mallam">Mallam</option>');
			$('#p_lga').append('<option value="Minjibir">Minjibir</option>');
			$('#p_lga').append('<option value="Nasarawa">Nasarawa</option>');
			$('#p_lga').append('<option value="Rano">Rano</option>');
			$('#p_lga').append('<option value="Rimin Gado">Rimin Gado</option>');
			$('#p_lga').append('<option value="Rogo">Rogo</option>');
			$('#p_lga').append('<option value="Shanono">Shanono</option>');
			$('#p_lga').append('<option value="Sumaila">Sumaila</option>');
			$('#p_lga').append('<option value="Takali">Takali</option>');
			$('#p_lga').append('<option value="Tarauni">Tarauni</option>');
			$('#p_lga').append('<option value="Tofa">Tofa</option>');
			$('#p_lga').append('<option value="Tsanyawa">Tsanyawa</option>');
			$('#p_lga').append('<option value="Tudun Wada">Tudun Wada</option>');
			$('#p_lga').append('<option value="Ungogo">Ungogo</option>');
			$('#p_lga').append('<option value="Warawa">Warawa</option>');
			$('#p_lga').append('<option value="Wudil">Wudil</option>');
		}
		else if(p_state=="KATSINA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Bakori">Bakori</option>');
			$('#p_lga').append('<option value="Batagarawa">Batagarawa</option>');
			$('#p_lga').append('<option value="Batsari">Batsari</option>');
			$('#p_lga').append('<option value="Baure">Baure</option>');
			$('#p_lga').append('<option value="Bindawa">Bindawa</option>');
			$('#p_lga').append('<option value="Charanchi">Charanchi</option>');
			$('#p_lga').append('<option value="Dandume">Dandume</option>');
			$('#p_lga').append('<option value="Danja">Danja</option>');
			$('#p_lga').append('<option value="Dan Musa">Dan Musa</option>');
			$('#p_lga').append('<option value="Daura">Daura</option>');
			$('#p_lga').append('<option value="Dutsi">Dutsi</option>');
			$('#p_lga').append('<option value="Dutsin-Ma">Dutsin-Ma</option>');
			$('#p_lga').append('<option value="Faskari">Faskari</option>');
			$('#p_lga').append('<option value="Funtua">Funtua</option>');
			$('#p_lga').append('<option value="Ingawa">Ingawa</option>');
			$('#p_lga').append('<option value="Jibia">Jibia</option>');
			$('#p_lga').append('<option value="Kafur">Kafur</option>');
			$('#p_lga').append('<option value="Kaita">Kaita</option>');
			$('#p_lga').append('<option value="Kankara">Kankara</option>');
			$('#p_lga').append('<option value="Kankia">Kankia</option>');
			$('#p_lga').append('<option value="Katsina">Katsina</option>');
			$('#p_lga').append('<option value="Kurfi">Kurfi</option>');
			$('#p_lga').append('<option value="Kusada">Kusada</option>');
			$('#p_lga').append('<option value="Mai-Adua">Mai-Adua</option>');
			$('#p_lga').append('<option value="Malumfashi">Malumfashi</option>');
			$('#p_lga').append('<option value="Mani">Mani</option>');
			$('#p_lga').append('<option value="Mashi">Mashi</option>');
			$('#p_lga').append('<option value="Matazuu">Matazuu</option>');
			$('#p_lga').append('<option value="Musawa">Musawa</option>');
			$('#p_lga').append('<option value="Rimi">Rimi</option>');
			$('#p_lga').append('<option value="Sabuwa">Sabuwa</option>');
			$('#p_lga').append('<option value="Safana">Safana</option>');
			$('#p_lga').append('<option value="Sandamu">Sandamu</option>');
			$('#p_lga').append('<option value="Zango">Zango</option>');
		}
		else if(p_state=="KEBBI"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Aleiro">Aleiro</option>');
			$('#p_lga').append('<option value="Arewa-Dandi">Arewa-Dandi</option>');
			$('#p_lga').append('<option value="Argungu">Argungu</option>');
			$('#p_lga').append('<option value="Augie">Augie</option>');
			$('#p_lga').append('<option value="Bagudo">Bagudo</option>');
			$('#p_lga').append('<option value="Birnin Kebbi">Birnin Kebbi</option>');
			$('#p_lga').append('<option value="Bunza">Bunza</option>');
			$('#p_lga').append('<option value="Dandi">Dandi</option>');
			$('#p_lga').append('<option value="Fakai">Fakai</option>');
			$('#p_lga').append('<option value="Gwandu">Gwandu</option>');
			$('#p_lga').append('<option value="Jega">Jega</option>');
			$('#p_lga').append('<option value="Kalgo">Kalgo</option>');
			$('#p_lga').append('<option value="Koko/Besse">Koko/Besse</option>');
			$('#p_lga').append('<option value="Maiyama">Maiyama</option>');
			$('#p_lga').append('<option value="Ngaski">Ngaski</option>');
			$('#p_lga').append('<option value="Sakaba">Sakaba</option>');
			$('#p_lga').append('<option value="Shanga">Shanga</option>');
			$('#p_lga').append('<option value="Suru">Suru</option>');
			$('#p_lga').append('<option value="Wasagu/Danko">Wasagu/Danko</option>');
			$('#p_lga').append('<option value="Yauri">Yauri</option>');
			$('#p_lga').append('<option value="Zuru">Zuru</option>');
		}
		else if(p_state=="KOGI"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Adavi">Adavi</option>');
			$('#p_lga').append('<option value="Ajaokuta">Ajaokuta</option>');
			$('#p_lga').append('<option value="Ankpa">Ankpa</option>');
			$('#p_lga').append('<option value="Bassa">Bassa</option>');
			$('#p_lga').append('<option value="Dekina">Dekina</option>');
			$('#p_lga').append('<option value="Ibaji">Ibaji</option>');
			$('#p_lga').append('<option value="Idah">Idah</option>');
			$('#p_lga').append('<option value="Igalamela-Odolu">Igalamela-Odolu</option>');
			$('#p_lga').append('<option value="Ijumu">Ijumu</option>');
			$('#p_lga').append('<option value="Kabba/Bunu">Kabba/Bunu</option>');
			$('#p_lga').append('<option value="Kogi">Kogi</option>');
			$('#p_lga').append('<option value="Lokoja">Lokoja</option>');
			$('#p_lga').append('<option value="Mopa-Muro">Mopa-Muro</option>');
			$('#p_lga').append('<option value="Ofu">Ofu</option>');
			$('#p_lga').append('<option value="Ogori/Mangongo">Ogori/Mangongo</option>');
			$('#p_lga').append('<option value="Okehi">Okehi</option>');
			$('#p_lga').append('<option value="Okene">Okene</option>');
			$('#p_lga').append('<option value="Olamabolo">Olamabolo</option>');
			$('#p_lga').append('<option value="Omala">Omala</option>');
			$('#p_lga').append('<option value="Yagba East">Yagba East</option>');
			$('#p_lga').append('<option value="Yagba West">Yagba West</option>');
		}
		else if(p_state=="KWARA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Asa">Asa</option>');
			$('#p_lga').append('<option value="Baruten">Baruten</option>');
			$('#p_lga').append('<option value="Edu">Edu</option>');
			$('#p_lga').append('<option value="Ekiti">Ekiti</option>');
			$('#p_lga').append('<option value="Ifelodun">Ifelodun</option>');
			$('#p_lga').append('<option value="Ilorin East">Ilorin East</option>');
			$('#p_lga').append('<option value="Ilorin South">Ilorin South</option>');
			$('#p_lga').append('<option value="Ilorin West">Ilorin West</option>');
			$('#p_lga').append('<option value="Irepodun">Irepodun</option>');
			$('#p_lga').append('<option value="Isin">Isin</option>');
			$('#p_lga').append('<option value="Kaiama">Kaiama</option>');
			$('#p_lga').append('<option value="Moro">Moro</option>');
			$('#p_lga').append('<option value="Offa">Offa</option>');
			$('#p_lga').append('<option value="Oke-Ero">Oke-Ero</option>');
			$('#p_lga').append('<option value="Oyun">Oyun</option>');
			$('#p_lga').append('<option value="Pategi">Pategi</option>');
		}
		else if(p_state=="LAGOS"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Agege">Agege</option>');
			$('#p_lga').append('<option value="Ajeromi-Ifelodun">Ajeromi-Ifelodun</option>');
			$('#p_lga').append('<option value="Alimosho">Alimosho</option>');
			$('#p_lga').append('<option value="Amuwo-Odofin">Amuwo-Odofin</option>');
			$('#p_lga').append('<option value="Apapa">Apapa</option>');
			$('#p_lga').append('<option value="Badagry">Badagry</option>');
			$('#p_lga').append('<option value="Epe">Epe</option>');
			$('#p_lga').append('<option value="Eti-Osa">Eti-Osa</option>');
			$('#p_lga').append('<option value="Ibeju/Lekki">Ibeju/Lekki</option>');
			$('#p_lga').append('<option value="Ifako-Ijaye">Ifako-Ijaye</option>');
			$('#p_lga').append('<option value="Ikeja">Ikeja</option>');
			$('#p_lga').append('<option value="Ikorodu">Ikorodu</option>');
			$('#p_lga').append('<option value="Kosofe">Kosofe</option>');
			$('#p_lga').append('<option value="Lagos Island">Lagos Island</option>');
			$('#p_lga').append('<option value="Lagos Mainland">Lagos Mainland</option>');
			$('#p_lga').append('<option value="Mushin">Mushin</option>');
			$('#p_lga').append('<option value="Ojo">Ojo</option>');
			$('#p_lga').append('<option value="Oshodi-Isolo">Oshodi-Isolo</option>');
			$('#p_lga').append('<option value="Shomolu">Shomolu</option>');
			$('#p_lga').append('<option value="Surulere">Surulere</option>');
		}
		else if(p_state=="NASSARAWA"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Akwanga">Akwanga</option>');
			$('#p_lga').append('<option value="Awe">Awe</option>');
			$('#p_lga').append('<option value="Doma">Doma</option>');
			$('#p_lga').append('<option value="Karu">Karu</option>');
			$('#p_lga').append('<option value="Keana">Keana</option>');
			$('#p_lga').append('<option value="Keffi">Keffi</option>');
			$('#p_lga').append('<option value="Kokona">Kokona</option>');
			$('#p_lga').append('<option value="Lafia">Lafia</option>');
			$('#p_lga').append('<option value="Nasarawa">Nasarawa</option>');
			$('#p_lga').append('<option value="Nasarawa-Eggon">Nasarawa-Eggon</option>');
			$('#p_lga').append('<option value="Obi">Obi</option>');
			$('#p_lga').append('<option value="Toto">Toto</option>');
			$('#p_lga').append('<option value="Wamba">Wamba</option>');
		}
		else if(p_state=="NIGER"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Agaie">Agaie</option>');
			$('#p_lga').append('<option value="Agwara">Agwara</option>');
			$('#p_lga').append('<option value="Bida">Bida</option>');
			$('#p_lga').append('<option value="Borgu">Borgu</option>');
			$('#p_lga').append('<option value="Bosso">Bosso</option>');
			$('#p_lga').append('<option value="Chanchaga">Chanchaga</option>');
			$('#p_lga').append('<option value="Edati">Edati</option>');
			$('#p_lga').append('<option value="Gbako">Gbako</option>');
			$('#p_lga').append('<option value="Gurara">Gurara</option>');
			$('#p_lga').append('<option value="Katcha">Katcha</option>');
			$('#p_lga').append('<option value="Kontagora">Kontagora</option>');
			$('#p_lga').append('<option value="Lapai">Lapai</option>');
			$('#p_lga').append('<option value="Lavun">Lavun</option>');
			$('#p_lga').append('<option value="Magama">Magama</option>');
			$('#p_lga').append('<option value="Mariga">Mariga</option>');
			$('#p_lga').append('<option value="Mashegu">Mashegu</option>');
			$('#p_lga').append('<option value="Mokwa">Mokwa</option>');
			$('#p_lga').append('<option value="Muya">Muya</option>');
			$('#p_lga').append('<option value="Pailoro">Pailoro</option>');
			$('#p_lga').append('<option value="Rafi">Rafi</option>');
			$('#p_lga').append('<option value="Rijau">Rijau</option>');
			$('#p_lga').append('<option value="Shiroro">Shiroro</option>');
			$('#p_lga').append('<option value="Suleja">Suleja</option>');
			$('#p_lga').append('<option value="Tafa">Tafa</option>');
			$('#p_lga').append('<option value="Wushishi">Wushishi</option>');
		}
		else if(p_state=="OGUN"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Abeokuta North">Abeokuta North</option>');
			$('#p_lga').append('<option value="Abeokuta South">Abeokuta South</option>');
			$('#p_lga').append('<option value="Ado-Odo/Ota">Ado-Odo/Ota</option>');
			$('#p_lga').append('<option value="Egbado North">Egbado North</option>');
			$('#p_lga').append('<option value="Egbado South">Egbado South</option>');
			$('#p_lga').append('<option value="Ewekoro">Ewekoro</option>');
			$('#p_lga').append('<option value="Ifo">Ifo</option>');
			$('#p_lga').append('<option value="Ijebu East">Ijebu East</option>');
			$('#p_lga').append('<option value="Ijebu North">Ijebu North</option>');
			$('#p_lga').append('<option value="Ijebu North East">Ijebu North East</option>');
			$('#p_lga').append('<option value="Ijebu Ode">Ijebu Ode</option>');
			$('#p_lga').append('<option value="Ikenne">Ikenne</option>');
			$('#p_lga').append('<option value="Imeko-Afon">Imeko-Afon</option>');
			$('#p_lga').append('<option value="Ipokia">Ipokia</option>');
			$('#p_lga').append('<option value="Obafemi-Owode">Obafemi-Owode</option>');
			$('#p_lga').append('<option value="Odeda">Odeda</option>');
			$('#p_lga').append('<option value="Odogbolu">Odogbolu</option>');
			$('#p_lga').append('<option value="Ogun Waterside">Ogun Waterside</option>');
			$('#p_lga').append('<option value="Remo North">Remo North</option>');
			$('#p_lga').append('<option value="Shagamu">Shagamu</option>');
		}
		else if(p_state=="ONDO"){
			$('#p_lga').empty();			
			$('#p_lga').append('<option value="Akoko North East">Akoko North East</option>');
			$('#p_lga').append('<option value="Akoko North West">Akoko North West</option>');
			$('#p_lga').append('<option value="Akoko South Akure East">Akoko South Akure East</option>');
			$('#p_lga').append('<option value="Akoko South West">Akoko South West</option>');
			$('#p_lga').append('<option value="Akure North">Akure North</option>');
			$('#p_lga').append('<option value="Akure South">Akure South</option>');
			$('#p_lga').append('<option value="Ese-Odo">Ese-Odo</option>');
			$('#p_lga').append('<option value="Idanre">Idanre</option>');
			$('#p_lga').append('<option value="Ifedore">Ifedore</option>');
			$('#p_lga').append('<option value="Ilaje">Ilaje</option>');
			$('#p_lga').append('<option value="Ile-Oluji">Ile-Oluji</option>');
			$('#p_lga').append('<option value="Okeigbo">Okeigbo</option>');
			$('#p_lga').append('<option value="Irele">Irele</option>');
			$('#p_lga').append('<option value="Odigbo">Odigbo</option>');
			$('#p_lga').append('<option value="Okitipupa">Okitipupa</option>');
			$('#p_lga').append('<option value="Ondo East">Ondo East</option>');
			$('#p_lga').append('<option value="Ondo West">Ondo West</option>');
			$('#p_lga').append('<option value="Ose">Ose</option>');
			$('#p_lga').append('<option value="Owo">Owo</option>');
		}
		else if(p_state=="OSUN"){
			$('#p_lga').empty();
			$('#p_lga').append('<option value="Aiyedade">Aiyedade</option>');
			$('#p_lga').append('<option value="Aiyedire">Aiyedire</option>');
			$('#p_lga').append('<option value="Atakumosa East">Atakumosa East</option>');
			$('#p_lga').append('<option value="Atakumosa West">Atakumosa West</option>');
			$('#p_lga').append('<option value="Boluwaduro">Boluwaduro</option>');
			$('#p_lga').append('<option value="Boripe">Boripe</option>');
			$('#p_lga').append('<option value="Ede North">Ede North</option>');
			$('#p_lga').append('<option value="Ede South">Ede South</option>');
			$('#p_lga').append('<option value="Egbedore">Egbedore</option>');
			$('#p_lga').append('<option value="Ejigbo">Ejigbo</option>');
			$('#p_lga').append('<option value="Ife Central">Ife Central</option>');
			$('#p_lga').append('<option value="Ife East">Ife East</option>');
			$('#p_lga').append('<option value="Ife North">Ife North</option>');
			$('#p_lga').append('<option value="Ife South">Ife South</option>');
			$('#p_lga').append('<option value="Ifedayo">Ifedayo</option>');
			$('#p_lga').append('<option value="Ifelodun">Ifelodun</option>');
			$('#p_lga').append('<option value="Ila">Ila</option>');
			$('#p_lga').append('<option value="Ilesha East">Ilesha East</option>');
			$('#p_lga').append('<option value="Ilesha West">Ilesha West</option>');
			$('#p_lga').append('<option value="Irepodun">Irepodun</option>');
			$('#p_lga').append('<option value="Irewole">Irewole</option>');
			$('#p_lga').append('<option value="Isokan">Isokan</option>');
			$('#p_lga').append('<option value="Iwo">Iwo</option>');
			$('#p_lga').append('<option value="Obokun">Obokun</option>');
			$('#p_lga').append('<option value="Odo-Otin">Odo-Otin</option>');
			$('#p_lga').append('<option value="Ola-Oluwa">Ola-Oluwa</option>');
			$('#p_lga').append('<option value="Olorunda">Olorunda</option>');
			$('#p_lga').append('<option value="Oriade">Oriade</option>');
			$('#p_lga').append('<option value="Orolu">Orolu</option>');
			$('#p_lga').append('<option value="Osogbo">Osogbo</option>');
		}
		else if(p_state=="OYO"){
			$('#p_lga').empty();
			$('#p_lga').append('<option value="Afijio">Afijio</option>');
			$('#p_lga').append('<option value="Akinyele">Akinyele</option>');
			$('#p_lga').append('<option value="Atiba">Atiba</option>');
			$('#p_lga').append('<option value="Atigbo">Atigbo</option>');
			$('#p_lga').append('<option value="Egbeda">Egbeda</option>');
			$('#p_lga').append('<option value="Ibadan North">Ibadan North</option>');
			$('#p_lga').append('<option value="Ibadan North East">Ibadan North East</option>');
			$('#p_lga').append('<option value="Ibadan North West">Ibadan North West</option>');
			$('#p_lga').append('<option value="Ibadan South East">Ibadan South East</option>');
			$('#p_lga').append('<option value="Ibadan South West">Ibadan South West</option>');
			$('#p_lga').append('<option value="IbadanCentral">IbadanCentral</option>');
			$('#p_lga').append('<option value="Ibarapa Central">Ibarapa Central</option>');
			$('#p_lga').append('<option value="Ibarapa East">Ibarapa East</option>');
			$('#p_lga').append('<option value="Ibarapa North">Ibarapa North</option>');
			$('#p_lga').append('<option value="Ido">Ido</option>');
			$('#p_lga').append('<option value="Irepo">Irepo</option>');
			$('#p_lga').append('<option value="Iseyin">Iseyin</option>');
			$('#p_lga').append('<option value="Itesiwaju">Itesiwaju</option>');
			$('#p_lga').append('<option value="Iwajowa">Iwajowa</option>');
			$('#p_lga').append('<option value="Kajola">Kajola</option>');
			$('#p_lga').append('<option value="Lagelu Ogbomosho North">Lagelu Ogbomosho North</option>');
			$('#p_lga').append('<option value="Ogbmosho South">Ogbmosho South</option>');
			$('#p_lga').append('<option value="Ogo Oluwa">Ogo Oluwa</option>');
			$('#p_lga').append('<option value="Olorunsogo">Olorunsogo</option>');
			$('#p_lga').append('<option value="Oluyole">Oluyole</option>');
			$('#p_lga').append('<option value="Ona-Ara">Ona-Ara</option>');
			$('#p_lga').append('<option value="Orelope">Orelope</option>');
			$('#p_lga').append('<option value="Ori Ire">Ori Ire</option>');
			$('#p_lga').append('<option value="Oyo East">Oyo East</option>');
			$('#p_lga').append('<option value="Oyo West">Oyo West</option>');
			$('#p_lga').append('<option value="Saki East">Saki East</option>');
			$('#p_lga').append('<option value="Saki West">Saki West</option>');
			$('#p_lga').append('<option value="Surulere">Surulere</option>');
		}
		else if(p_state=="PLATEAU"){
			$('#p_lga').empty();
			$('#p_lga').append('<option value="Barikin Ladi">Barikin Ladi</option>');
			$('#p_lga').append('<option value="Bassa">Bassa</option>');
			$('#p_lga').append('<option value="Bokkos">Bokkos</option>');
			$('#p_lga').append('<option value="Jos East">Jos East</option>');
			$('#p_lga').append('<option value="Jos North">Jos North</option>');
			$('#p_lga').append('<option value="Jos South">Jos South</option>');
			$('#p_lga').append('<option value="Kanam">Kanam</option>');
			$('#p_lga').append('<option value="Kanke">Kanke</option>');
			$('#p_lga').append('<option value="Langtang North">Langtang North</option>');
			$('#p_lga').append('<option value="Langtang South">Langtang South</option>');
			$('#p_lga').append('<option value="Mangu">Mangu</option>');
			$('#p_lga').append('<option value="Mikang">Mikang</option>');
			$('#p_lga').append('<option value="Pankshin">Pankshin</option>');
			$('#p_lga').append('<option value="Qua-an Pan">Qua-an Pan</option>');
			$('#p_lga').append('<option value="Riyom">Riyom</option>');
			$('#p_lga').append('<option value="Shendam">Shendam</option>');
			$('#p_lga').append('<option value="Wase">Wase</option>');
		}
		else if(p_state=="RIVERS"){
			$('#p_lga').empty();
			$('#p_lga').append('<option value="Abua/Odual">Abua/Odual</option>');
			$('#p_lga').append('<option value="Ahoada East">Ahoada East</option>');
			$('#p_lga').append('<option value="Ahoada West">Ahoada West</option>');
			$('#p_lga').append('<option value="Akuku Toru">Akuku Toru</option>');
			$('#p_lga').append('<option value="Andoni">Andoni</option>');
			$('#p_lga').append('<option value="Asari-Toru">Asari-Toru</option>');
			$('#p_lga').append('<option value="Bonny">Bonny</option>');
			$('#p_lga').append('<option value="Degema">Degema</option>');
			$('#p_lga').append('<option value="Eleme">Eleme</option>');
			$('#p_lga').append('<option value="Emohua">Emohua</option>');
			$('#p_lga').append('<option value="Etche">Etche</option>');
			$('#p_lga').append('<option value="Gokana">Gokana</option>');
			$('#p_lga').append('<option value="Ikwerre">Ikwerre</option>');
			$('#p_lga').append('<option value="Khana">Khana</option>');
			$('#p_lga').append('<option value="Obia/Akpor">Obia/Akpor</option>');
			$('#p_lga').append('<option value="Ogba/Egbema/Ndoni">Ogba/Egbema/Ndoni</option>');
			$('#p_lga').append('<option value="Ogu/Bolo">Ogu/Bolo</option>');
			$('#p_lga').append('<option value="Okrika">Okrika</option>');
			$('#p_lga').append('<option value="Omumma">Omumma</option>');
			$('#p_lga').append('<option value="Opobo/Nkoro">Opobo/Nkoro</option>');
			$('#p_lga').append('<option value="Oyigbo">Oyigbo</option>');
			$('#p_lga').append('<option value="Port-Harcourt">Port-Harcourt</option>');
			$('#p_lga').append('<option value="Tai">Tai</option>');
		}
		else if(p_state=="SOKOTO"){
			$('#p_lga').empty();
			$('#p_lga').append('<option value="Binji">Binji</option>');
			$('#p_lga').append('<option value="Bodinga">Bodinga</option>');
			$('#p_lga').append('<option value="Dange-shusi">Dange-shusi</option>');
			$('#p_lga').append('<option value="Gada">Gada</option>');
			$('#p_lga').append('<option value="Gawabawa">Gawabawa</option>');
			$('#p_lga').append('<option value="Goronyo">Goronyo</option>');
			$('#p_lga').append('<option value="Gudu">Gudu</option>');
			$('#p_lga').append('<option value="Illela">Illela</option>');
			$('#p_lga').append('<option value="Isa">Isa</option>');
			$('#p_lga').append('<option value="Kebbe">Kebbe</option>');
			$('#p_lga').append('<option value="Kware">Kware</option>');
			$('#p_lga').append('<option value="Rabah">Rabah</option>');
			$('#p_lga').append('<option value="Sabon birni">Sabon birni</option>');
			$('#p_lga').append('<option value="Shagari">Shagari</option>');
			$('#p_lga').append('<option value="Silame">Silame</option>');
			$('#p_lga').append('<option value="Sokoto North">Sokoto North</option>');
			$('#p_lga').append('<option value="Sokoto South">Sokoto South</option>');
			$('#p_lga').append('<option value="Tambuwal">Tambuwal</option>');
			$('#p_lga').append('<option value="Tangaza">Tangaza</option>');
			$('#p_lga').append('<option value="Tureta">Tureta</option>');
			$('#p_lga').append('<option value="Wamako">Wamako</option>');
			$('#p_lga').append('<option value="Wurno">Wurno</option>');
			$('#p_lga').append('<option value="Yabo">Yabo</option>');
		}
		else if(p_state=="TARABA"){
			$('#p_lga').empty();
			$('#p_lga').append('<option value="Ardo-kola">Ardo-kola</option>');
			$('#p_lga').append('<option value="Bali">Bali</option>');
			$('#p_lga').append('<option value="Donga">Donga</option>');
			$('#p_lga').append('<option value="Gashaka">Gashaka</option>');
			$('#p_lga').append('<option value="Gassol">Gassol</option>');
			$('#p_lga').append('<option value="Ibi">Ibi</option>');
			$('#p_lga').append('<option value="Jalingo">Jalingo</option>');
			$('#p_lga').append('<option value="Karin-Lamido">Karin-Lamido</option>');
			$('#p_lga').append('<option value="Kurmi">Kurmi</option>');
			$('#p_lga').append('<option value="Lau">Lau</option>');
			$('#p_lga').append('<option value="Sardauna">Sardauna</option>');
			$('#p_lga').append('<option value="Takum">Takum</option>');
			$('#p_lga').append('<option value="Ussa">Ussa</option>');
			$('#p_lga').append('<option value="Wukari">Wukari</option>');
			$('#p_lga').append('<option value="Yorro">Yorro</option>');
			$('#p_lga').append('<option value="Zing">Zing</option>');
		}
		else if(p_state=="YOBE"){
			$('#p_lga').empty();
			
			$('#p_lga').append('<option value="Bade">Bade</option>');
			$('#p_lga').append('<option value="Bursari">Bursari</option>');
			$('#p_lga').append('<option value="Damaturu">Damaturu</option>');
			$('#p_lga').append('<option value="Fika">Fika</option>');
			$('#p_lga').append('<option value="Fune">Fune</option>');
			$('#p_lga').append('<option value="Geidam">Geidam</option>');
			$('#p_lga').append('<option value="Gujba">Gujba</option>');
			$('#p_lga').append('<option value="Gulani">Gulani</option>');
			$('#p_lga').append('<option value="Jakusko">Jakusko</option>');
			$('#p_lga').append('<option value="Karasuwa">Karasuwa</option>');
			$('#p_lga').append('<option value="Karawa">Karawa</option>');
			$('#p_lga').append('<option value="Machina">Machina</option>');
			$('#p_lga').append('<option value="Nangere">Nangere</option>');
			$('#p_lga').append('<option value="Nguru Potiskum">Nguru Potiskum</option>');
			$('#p_lga').append('<option value="Tarmua">Tarmua</option>');
			$('#p_lga').append('<option value="Yunusari">Yunusari</option>');
			$('#p_lga').append('<option value="Yusufari">Yusufari</option>');
		}
		else if(p_state=="ZAMFARA"){
			$('#p_lga').empty();
			$('#p_lga').append('<option value="Anka">Anka</option>');
			$('#p_lga').append('<option value="Bakura">Bakura</option>');
			$('#p_lga').append('<option value="Birnin Magaji">Birnin Magaji</option>');
			$('#p_lga').append('<option value="Bukkuyum">Bukkuyum</option>');
			$('#p_lga').append('<option value="Bungudu">Bungudu</option>');
			$('#p_lga').append('<option value="Gummi">Gummi</option>');
			$('#p_lga').append('<option value="Gusau">Gusau</option>');
			$('#p_lga').append('<option value="Kaura">Kaura</option>');
			$('#p_lga').append('<option value="Maradun">Maradun</option>');
			$('#p_lga').append('<option value="Maru">Maru</option>');
			$('#p_lga').append('<option value="Namoda">Namoda</option>');
			$('#p_lga').append('<option value="Shinkafi">Shinkafi</option>');
			$('#p_lga').append('<option value="Talata Mafara">Talata Mafara</option>');
			$('#p_lga').append('<option value="Tsafe">Tsafe</option>');
			$('#p_lga').append('<option value="Zurmi">Zurmi</option>');
		}
	});
	
	
	
});