# services:
#   app:
#     build: .
#     container_name: php_app
#     ports:
#       - "8080:80"
#     volumes:
#       - .:/var/www/html
#     depends_on:
#       - db

#   db:
#     image: postgres:16
#     container_name: postgres_db
#     environment:
#       POSTGRES_DB: ufers
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: your_password
#     volumes:
#       - pgdata:/var/lib/postgresql/data
#       - ./db-init:/docker-entrypoint-initdb.d/

# volumes:
#   pgdata:

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: ufers
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php_app:
    build: .
    container_name: php_app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql_db

volumes:
  mysql_data:
